project_id = "mmigoucitdlfsmbbrtfs"

[functions.generate-report]
verify_jwt = true

[functions.generate-final-report]
verify_jwt = true

[functions.process-document-ocr]
verify_jwt = true

[functions.anonymize-document]
verify_jwt = true

[functions.clean-anonymized-text]
verify_jwt = true
